{% set name = "eo-harvest" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/naiad/eo_harvest/-/archive/{{ version }}/eo_harvest-{{ version }}.tar.gz
  sha256: b7cd25b5c23901b865b98eeb8d9ebce21a8a440d5f6ceccb49d48e647abb3ca7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  
requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy
    - pandas
    - xarray >=0.15
    - shapely >=1.2.18
    - python-dateutil >=2.1
    - cftime
    - sphinx-autodoc-typehints
    - cartopy
    - lxml
    - bs4
    - podaacpy
    - pyyaml

    
test:
  imports:
    - eo_harvest
    
about:
  home: https://gitlab.ifremer.fr/naiad/eo_harvest
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: eo-harvest is a python package that allows to perform data searches from different online Earth Obervation (EO) data providers, with a unified API and simple spatial and temporal criteria.

extra:
  recipe-maintainers:
    - marie59
